/*
* generated by Xtext
*/
package org.ddmore.mdl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MdlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.ddmore.mdl.ui.internal.MdlActivator.getInstance().getInjector("org.ddmore.mdl.Mdl");
	}
	
}
