<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mdl" nsURI="http://www.ddmore.org/mdl/Mdl" nsPrefix="mdl">
  <eClassifiers xsi:type="ecore:EClass" name="mcl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//mcl_obj" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mcl_obj">
    <eStructuralFeatures xsi:type="ecore:EReference" name="model_obj" eType="#//model_obj"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param_obj" eType="#//param_obj"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_obj" eType="#//data_obj"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task_obj" eType="#//task_obj"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tel_obj" eType="#//tel_obj"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="model_obj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//model_obj_block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="param_obj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//param_obj_block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="data_obj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//data_obj_block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="task_obj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//task_obj_block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="tel_obj">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//block_statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="model_obj_block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individual_model_obj_block"
        eType="#//individual_model_obj_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model_prediction_obj_block"
        eType="#//model_prediction_obj_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="random_variable_definition_block"
        eType="#//random_variable_definition_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_variables_block"
        eType="#//input_variables_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="structural_parameters_block"
        eType="#//structural_parameters_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variability_parameters_block"
        eType="#//variability_parameters_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_variables_block"
        eType="#//output_variables_block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="group_variables" eType="#//group_variables"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="observation_block" eType="#//observation_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estimation_block" eType="#//estimation_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulation_block" eType="#//simulation_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="individual_model_obj_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="model_prediction_obj_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//model_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="random_variable_definition_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="input_variables_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="structural_parameters_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variability_parameters_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="output_variables_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="group_variables">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="observation_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="estimation_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="simulation_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="param_obj_block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="structural_block" eType="#//structural_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variability_block" eType="#//variability_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="structural_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variability_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//variability_block_content"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="data_obj_block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header_block" eType="#//header_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="file_block" eType="#//file_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="header_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="file_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//file_block_content"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="task_obj_block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function_declaration" eType="#//function_declaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters_block" eType="#//parameters_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="data_block" eType="#//data_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="parameters_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="data_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="model_block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//model_block_statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="model_block_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//block_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ode_block" eType="#//ode_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="library_block" eType="#//library_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="library_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ode_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variability_block_content">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//variability_block_statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variability_block_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block_statement" eType="#//block_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block_block" eType="#//block_subblock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diag_block" eType="#//diag_subblock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="block_subblock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//variability_subblock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="diag_subblock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//variability_subblock"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variability_subblock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="file_block_content">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//file_block_statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="file_block_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//block_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inline_block" eType="#//inline_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="design_block" eType="#//design_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rsscript_block" eType="#//rsscript_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="inline_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//inline_block_content"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="design_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="rsscript_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="inline_block_content">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiers" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="function_declaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="formal_arguments" eType="#//formal_arguments"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function_body" eType="#//function_body"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="function_body">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//function_subblock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="function_subblock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="estimate_defn" eType="#//block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulate_defn" eType="#//block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="formal_arguments">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifiers" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="function_call">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="funct_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="block">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//block_statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="block_statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable_declaration" eType="#//variable_declaration"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function_call" eType="#//function_call"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verbatim_block" eType="#//verbatim_block"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="verbatim_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//target_block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external_code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="target_block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="external_code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variable_declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//variable_name"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//any_expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="random_list" eType="#//random_list"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="any_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="list" eType="#//list" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ode_list" eType="#//ode_list"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="random_list" eType="#//random_list"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditional_expression"
        eType="#//conditional_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string_expression" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="list">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ode_list">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="random_list">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" eType="#//arguments"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="arguments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1"
        eType="#//argument" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="argument">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//any_expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" eType="#//block"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="par_expression" eType="#//par_expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="if_statement" eType="#//block_statement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="else_statement" eType="#//block_statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="par_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="conditional_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditional_or_expression"
        eType="#//conditional_or_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression1" eType="#//expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression2" eType="#//expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="conditional_or_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditional_and_expression"
        upperBound="-1" eType="#//conditional_and_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="conditional_and_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relational_expression"
        upperBound="-1" eType="#//relational_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="relational_expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolean" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="additive_expression" upperBound="-1"
        eType="#//additive_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relational_op" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="additive_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicative_expression"
        upperBound="-1" eType="#//multiplicative_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additive_op" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="multiplicative_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="power_expression" upperBound="-1"
        eType="#//power_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicative_op" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="power_expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unary_expression" upperBound="-1"
        eType="#//unary_expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="power_op" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="unary_expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unary_expression" eType="#//unary_expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="par_expression" eType="#//par_expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function_call" eType="#//function_call"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primary" eType="#//primary"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="primary">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" eType="#//variable_name"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="variable_name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selector" upperBound="-1"
        eType="#//selector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="selector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//primary" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
