/*
 * generated by Xtext
 */
package org.ddmore.mdl.scoping;
/*
import java.util.ArrayList;
import java.util.List;

import org.ddmore.mdl.mdl.UnaryExpression;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;*/
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
		
public class MdlScopeProvider extends AbstractDeclarativeScopeProvider {
	/*IScope getScope(UnaryExpression u, EReference ref){
		List<EObject> crossRefTargets = new ArrayList<EObject>();
		return Scopes.scopeFor(crossRefTargets);
	}*/
}
