/*
 * generated by Xtext
 */
package org.ddmore.mdl.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
		
public class MdlScopeProvider extends AbstractDeclarativeScopeProvider {
	/*IScope scope_FullyQualifiedSymbolName_object(Mcl mcl, EReference ref){
		List<EObject> crossRefTargets = Lists.newArrayList();
		for (MclObject m: mcl.getObjects()){
			crossRefTargets.add(m.getObjectName());
		}
		return Scopes.scopeFor(crossRefTargets);
	}*/
}
