/*
* generated by Xtext
*/
package eu.ddmore.mdl;

import com.google.inject.Injector;

import eu.ddmore.mdllib.MdlLibInjectorProvider;

public class MdlAndLibInjectorProvider extends MdlInjectorProvider{ 

	@Override
	protected Injector internalCreateInjector(){
		new MdlLibInjectorProvider().getInjector();
		return super.internalCreateInjector();
	}

}
