/*
 * generated by Xtext
 */
package org.ddmore.mdl;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MdlRuntimeModule extends org.ddmore.mdl.AbstractMdlRuntimeModule {

	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider(){
		return NullGlobalScopeProvider.class;
	}
	
}
