/*
 * generated by Xtext
 */
package org.ddmore.mdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MdlRuntimeModule extends org.ddmore.mdl.AbstractMdlRuntimeModule {

}
