/*
* generated by Xtext
*/
package org.ddmore.mdl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.ddmore.mdl.services.MdlGrammarAccess;

public class MdlParser extends AbstractContentAssistParser {
	
	@Inject
	private MdlGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.ddmore.mdl.ui.contentassist.antlr.internal.InternalMdlParser createParser() {
		org.ddmore.mdl.ui.contentassist.antlr.internal.InternalMdlParser result = new org.ddmore.mdl.ui.contentassist.antlr.internal.InternalMdlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMcl_objAccess().getAlternatives(), "rule__Mcl_obj__Alternatives");
					put(grammarAccess.getModel_obj_blockAccess().getAlternatives(), "rule__Model_obj_block__Alternatives");
					put(grammarAccess.getParam_obj_blockAccess().getAlternatives(), "rule__Param_obj_block__Alternatives");
					put(grammarAccess.getData_obj_blockAccess().getAlternatives(), "rule__Data_obj_block__Alternatives");
					put(grammarAccess.getTask_obj_blockAccess().getAlternatives(), "rule__Task_obj_block__Alternatives");
					put(grammarAccess.getModel_block_statementAccess().getAlternatives(), "rule__Model_block_statement__Alternatives");
					put(grammarAccess.getVariability_block_statementAccess().getAlternatives(), "rule__Variability_block_statement__Alternatives");
					put(grammarAccess.getFile_block_statementAccess().getAlternatives(), "rule__File_block_statement__Alternatives");
					put(grammarAccess.getInline_block_contentAccess().getValuesAlternatives_3_0(), "rule__Inline_block_content__ValuesAlternatives_3_0");
					put(grammarAccess.getFunction_subblockAccess().getAlternatives(), "rule__Function_subblock__Alternatives");
					put(grammarAccess.getBlock_statementAccess().getAlternatives(), "rule__Block_statement__Alternatives");
					put(grammarAccess.getVerbatim_blockAccess().getAlternatives_2(), "rule__Verbatim_block__Alternatives_2");
					put(grammarAccess.getTarget_languageAccess().getAlternatives(), "rule__Target_language__Alternatives");
					put(grammarAccess.getVariable_declarationAccess().getAlternatives_1(), "rule__Variable_declaration__Alternatives_1");
					put(grammarAccess.getAny_expressionAccess().getAlternatives(), "rule__Any_expression__Alternatives");
					put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
					put(grammarAccess.getArgumentAccess().getAlternatives(), "rule__Argument__Alternatives");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getRelational_expressionAccess().getAlternatives_1(), "rule__Relational_expression__Alternatives_1");
					put(grammarAccess.getUnary_expressionAccess().getAlternatives(), "rule__Unary_expression__Alternatives");
					put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
					put(grammarAccess.getRelational_opAccess().getAlternatives(), "rule__Relational_op__Alternatives");
					put(grammarAccess.getMultiplicative_opAccess().getAlternatives(), "rule__Multiplicative_op__Alternatives");
					put(grammarAccess.getAdditive_opAccess().getAlternatives(), "rule__Additive_op__Alternatives");
					put(grammarAccess.getUnary_opAccess().getAlternatives(), "rule__Unary_op__Alternatives");
					put(grammarAccess.getNUMBERAccess().getAlternatives(), "rule__NUMBER__Alternatives");
					put(grammarAccess.getModel_objAccess().getGroup(), "rule__Model_obj__Group__0");
					put(grammarAccess.getParam_objAccess().getGroup(), "rule__Param_obj__Group__0");
					put(grammarAccess.getData_objAccess().getGroup(), "rule__Data_obj__Group__0");
					put(grammarAccess.getTask_objAccess().getGroup(), "rule__Task_obj__Group__0");
					put(grammarAccess.getTel_objAccess().getGroup(), "rule__Tel_obj__Group__0");
					put(grammarAccess.getIndividual_model_obj_blockAccess().getGroup(), "rule__Individual_model_obj_block__Group__0");
					put(grammarAccess.getModel_prediction_obj_blockAccess().getGroup(), "rule__Model_prediction_obj_block__Group__0");
					put(grammarAccess.getRandom_variable_definition_blockAccess().getGroup(), "rule__Random_variable_definition_block__Group__0");
					put(grammarAccess.getInput_variables_blockAccess().getGroup(), "rule__Input_variables_block__Group__0");
					put(grammarAccess.getStructural_parameters_blockAccess().getGroup(), "rule__Structural_parameters_block__Group__0");
					put(grammarAccess.getVariability_parameters_blockAccess().getGroup(), "rule__Variability_parameters_block__Group__0");
					put(grammarAccess.getOutput_variables_blockAccess().getGroup(), "rule__Output_variables_block__Group__0");
					put(grammarAccess.getGroup_variablesAccess().getGroup(), "rule__Group_variables__Group__0");
					put(grammarAccess.getObservation_blockAccess().getGroup(), "rule__Observation_block__Group__0");
					put(grammarAccess.getEstimation_blockAccess().getGroup(), "rule__Estimation_block__Group__0");
					put(grammarAccess.getSimulation_blockAccess().getGroup(), "rule__Simulation_block__Group__0");
					put(grammarAccess.getStructural_blockAccess().getGroup(), "rule__Structural_block__Group__0");
					put(grammarAccess.getVariability_blockAccess().getGroup(), "rule__Variability_block__Group__0");
					put(grammarAccess.getHeader_blockAccess().getGroup(), "rule__Header_block__Group__0");
					put(grammarAccess.getFile_blockAccess().getGroup(), "rule__File_block__Group__0");
					put(grammarAccess.getParameters_blockAccess().getGroup(), "rule__Parameters_block__Group__0");
					put(grammarAccess.getData_blockAccess().getGroup(), "rule__Data_block__Group__0");
					put(grammarAccess.getModel_blockAccess().getGroup(), "rule__Model_block__Group__0");
					put(grammarAccess.getLibrary_blockAccess().getGroup(), "rule__Library_block__Group__0");
					put(grammarAccess.getOde_blockAccess().getGroup(), "rule__Ode_block__Group__0");
					put(grammarAccess.getVariability_block_contentAccess().getGroup(), "rule__Variability_block_content__Group__0");
					put(grammarAccess.getBlock_subblockAccess().getGroup(), "rule__Block_subblock__Group__0");
					put(grammarAccess.getDiag_subblockAccess().getGroup(), "rule__Diag_subblock__Group__0");
					put(grammarAccess.getVariability_subblockAccess().getGroup(), "rule__Variability_subblock__Group__0");
					put(grammarAccess.getFile_block_contentAccess().getGroup(), "rule__File_block_content__Group__0");
					put(grammarAccess.getInline_blockAccess().getGroup(), "rule__Inline_block__Group__0");
					put(grammarAccess.getDesign_blockAccess().getGroup(), "rule__Design_block__Group__0");
					put(grammarAccess.getRsscript_blockAccess().getGroup(), "rule__Rsscript_block__Group__0");
					put(grammarAccess.getInline_block_contentAccess().getGroup(), "rule__Inline_block_content__Group__0");
					put(grammarAccess.getFunction_declarationAccess().getGroup(), "rule__Function_declaration__Group__0");
					put(grammarAccess.getFunction_bodyAccess().getGroup(), "rule__Function_body__Group__0");
					put(grammarAccess.getFunction_subblockAccess().getGroup_0(), "rule__Function_subblock__Group_0__0");
					put(grammarAccess.getFunction_subblockAccess().getGroup_1(), "rule__Function_subblock__Group_1__0");
					put(grammarAccess.getFormal_argumentsAccess().getGroup(), "rule__Formal_arguments__Group__0");
					put(grammarAccess.getFormal_argumentsAccess().getGroup_1(), "rule__Formal_arguments__Group_1__0");
					put(grammarAccess.getFunction_callAccess().getGroup(), "rule__Function_call__Group__0");
					put(grammarAccess.getBlockAccess().getGroup(), "rule__Block__Group__0");
					put(grammarAccess.getVerbatim_blockAccess().getGroup(), "rule__Verbatim_block__Group__0");
					put(grammarAccess.getTarget_blockAccess().getGroup(), "rule__Target_block__Group__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup(), "rule__Variable_declaration__Group__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup_1_0(), "rule__Variable_declaration__Group_1_0__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getExpressionAccess().getGroup_1_1(), "rule__Expression__Group_1_1__0");
					put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
					put(grammarAccess.getOde_listAccess().getGroup(), "rule__Ode_list__Group__0");
					put(grammarAccess.getRandom_listAccess().getGroup(), "rule__Random_list__Group__0");
					put(grammarAccess.getArgumentsAccess().getGroup(), "rule__Arguments__Group__0");
					put(grammarAccess.getArgumentsAccess().getGroup_1(), "rule__Arguments__Group_1__0");
					put(grammarAccess.getArgumentAccess().getGroup_0(), "rule__Argument__Group_0__0");
					put(grammarAccess.getStatementAccess().getGroup_1(), "rule__Statement__Group_1__0");
					put(grammarAccess.getStatementAccess().getGroup_1_3(), "rule__Statement__Group_1_3__0");
					put(grammarAccess.getPar_expressionAccess().getGroup(), "rule__Par_expression__Group__0");
					put(grammarAccess.getConditional_expressionAccess().getGroup(), "rule__Conditional_expression__Group__0");
					put(grammarAccess.getConditional_expressionAccess().getGroup_1(), "rule__Conditional_expression__Group_1__0");
					put(grammarAccess.getConditional_or_expressionAccess().getGroup(), "rule__Conditional_or_expression__Group__0");
					put(grammarAccess.getConditional_or_expressionAccess().getGroup_1(), "rule__Conditional_or_expression__Group_1__0");
					put(grammarAccess.getConditional_and_expressionAccess().getGroup(), "rule__Conditional_and_expression__Group__0");
					put(grammarAccess.getConditional_and_expressionAccess().getGroup_1(), "rule__Conditional_and_expression__Group_1__0");
					put(grammarAccess.getRelational_expressionAccess().getGroup(), "rule__Relational_expression__Group__0");
					put(grammarAccess.getRelational_expressionAccess().getGroup_1_1(), "rule__Relational_expression__Group_1_1__0");
					put(grammarAccess.getRelational_expressionAccess().getGroup_1_1_1(), "rule__Relational_expression__Group_1_1_1__0");
					put(grammarAccess.getAdditive_expressionAccess().getGroup(), "rule__Additive_expression__Group__0");
					put(grammarAccess.getAdditive_expressionAccess().getGroup_1(), "rule__Additive_expression__Group_1__0");
					put(grammarAccess.getMultiplicative_expressionAccess().getGroup(), "rule__Multiplicative_expression__Group__0");
					put(grammarAccess.getMultiplicative_expressionAccess().getGroup_1(), "rule__Multiplicative_expression__Group_1__0");
					put(grammarAccess.getPower_expressionAccess().getGroup(), "rule__Power_expression__Group__0");
					put(grammarAccess.getPower_expressionAccess().getGroup_1(), "rule__Power_expression__Group_1__0");
					put(grammarAccess.getUnary_expressionAccess().getGroup_0(), "rule__Unary_expression__Group_0__0");
					put(grammarAccess.getVariable_nameAccess().getGroup(), "rule__Variable_name__Group__0");
					put(grammarAccess.getVariable_nameAccess().getGroup_2(), "rule__Variable_name__Group_2__0");
					put(grammarAccess.getSelectorAccess().getGroup(), "rule__Selector__Group__0");
					put(grammarAccess.getSelectorAccess().getGroup_2(), "rule__Selector__Group_2__0");
					put(grammarAccess.getMclAccess().getObjectsAssignment(), "rule__Mcl__ObjectsAssignment");
					put(grammarAccess.getMcl_objAccess().getModel_objAssignment_0(), "rule__Mcl_obj__Model_objAssignment_0");
					put(grammarAccess.getMcl_objAccess().getParam_objAssignment_1(), "rule__Mcl_obj__Param_objAssignment_1");
					put(grammarAccess.getMcl_objAccess().getData_objAssignment_2(), "rule__Mcl_obj__Data_objAssignment_2");
					put(grammarAccess.getMcl_objAccess().getTask_objAssignment_3(), "rule__Mcl_obj__Task_objAssignment_3");
					put(grammarAccess.getMcl_objAccess().getTel_objAssignment_4(), "rule__Mcl_obj__Tel_objAssignment_4");
					put(grammarAccess.getModel_objAccess().getIdentifierAssignment_0(), "rule__Model_obj__IdentifierAssignment_0");
					put(grammarAccess.getModel_objAccess().getBlocksAssignment_4(), "rule__Model_obj__BlocksAssignment_4");
					put(grammarAccess.getParam_objAccess().getIdentifierAssignment_0(), "rule__Param_obj__IdentifierAssignment_0");
					put(grammarAccess.getParam_objAccess().getBlocksAssignment_4(), "rule__Param_obj__BlocksAssignment_4");
					put(grammarAccess.getData_objAccess().getIdentifierAssignment_0(), "rule__Data_obj__IdentifierAssignment_0");
					put(grammarAccess.getData_objAccess().getBlocksAssignment_4(), "rule__Data_obj__BlocksAssignment_4");
					put(grammarAccess.getTask_objAccess().getIdentifierAssignment_0(), "rule__Task_obj__IdentifierAssignment_0");
					put(grammarAccess.getTask_objAccess().getBlocksAssignment_4(), "rule__Task_obj__BlocksAssignment_4");
					put(grammarAccess.getTel_objAccess().getIdentifierAssignment_0(), "rule__Tel_obj__IdentifierAssignment_0");
					put(grammarAccess.getTel_objAccess().getBlocksAssignment_4(), "rule__Tel_obj__BlocksAssignment_4");
					put(grammarAccess.getModel_obj_blockAccess().getIndividual_model_obj_blockAssignment_0(), "rule__Model_obj_block__Individual_model_obj_blockAssignment_0");
					put(grammarAccess.getModel_obj_blockAccess().getModel_prediction_obj_blockAssignment_1(), "rule__Model_obj_block__Model_prediction_obj_blockAssignment_1");
					put(grammarAccess.getModel_obj_blockAccess().getRandom_variable_definition_blockAssignment_2(), "rule__Model_obj_block__Random_variable_definition_blockAssignment_2");
					put(grammarAccess.getModel_obj_blockAccess().getInput_variables_blockAssignment_3(), "rule__Model_obj_block__Input_variables_blockAssignment_3");
					put(grammarAccess.getModel_obj_blockAccess().getStructural_parameters_blockAssignment_4(), "rule__Model_obj_block__Structural_parameters_blockAssignment_4");
					put(grammarAccess.getModel_obj_blockAccess().getVariability_parameters_blockAssignment_5(), "rule__Model_obj_block__Variability_parameters_blockAssignment_5");
					put(grammarAccess.getModel_obj_blockAccess().getOutput_variables_blockAssignment_6(), "rule__Model_obj_block__Output_variables_blockAssignment_6");
					put(grammarAccess.getModel_obj_blockAccess().getGroup_variablesAssignment_7(), "rule__Model_obj_block__Group_variablesAssignment_7");
					put(grammarAccess.getModel_obj_blockAccess().getObservation_blockAssignment_8(), "rule__Model_obj_block__Observation_blockAssignment_8");
					put(grammarAccess.getModel_obj_blockAccess().getEstimation_blockAssignment_9(), "rule__Model_obj_block__Estimation_blockAssignment_9");
					put(grammarAccess.getModel_obj_blockAccess().getSimulation_blockAssignment_10(), "rule__Model_obj_block__Simulation_blockAssignment_10");
					put(grammarAccess.getIndividual_model_obj_blockAccess().getIdentifierAssignment_0(), "rule__Individual_model_obj_block__IdentifierAssignment_0");
					put(grammarAccess.getIndividual_model_obj_blockAccess().getBlockAssignment_1(), "rule__Individual_model_obj_block__BlockAssignment_1");
					put(grammarAccess.getModel_prediction_obj_blockAccess().getIdentifierAssignment_0(), "rule__Model_prediction_obj_block__IdentifierAssignment_0");
					put(grammarAccess.getModel_prediction_obj_blockAccess().getBlockAssignment_1(), "rule__Model_prediction_obj_block__BlockAssignment_1");
					put(grammarAccess.getRandom_variable_definition_blockAccess().getIdentifierAssignment_0(), "rule__Random_variable_definition_block__IdentifierAssignment_0");
					put(grammarAccess.getRandom_variable_definition_blockAccess().getBlockAssignment_1(), "rule__Random_variable_definition_block__BlockAssignment_1");
					put(grammarAccess.getInput_variables_blockAccess().getIndentifierAssignment_0(), "rule__Input_variables_block__IndentifierAssignment_0");
					put(grammarAccess.getInput_variables_blockAccess().getBlockAssignment_1(), "rule__Input_variables_block__BlockAssignment_1");
					put(grammarAccess.getStructural_parameters_blockAccess().getIdentifierAssignment_0(), "rule__Structural_parameters_block__IdentifierAssignment_0");
					put(grammarAccess.getStructural_parameters_blockAccess().getBlockAssignment_1(), "rule__Structural_parameters_block__BlockAssignment_1");
					put(grammarAccess.getVariability_parameters_blockAccess().getIdentifierAssignment_0(), "rule__Variability_parameters_block__IdentifierAssignment_0");
					put(grammarAccess.getVariability_parameters_blockAccess().getBlockAssignment_1(), "rule__Variability_parameters_block__BlockAssignment_1");
					put(grammarAccess.getOutput_variables_blockAccess().getIdentifierAssignment_0(), "rule__Output_variables_block__IdentifierAssignment_0");
					put(grammarAccess.getOutput_variables_blockAccess().getBlockAssignment_1(), "rule__Output_variables_block__BlockAssignment_1");
					put(grammarAccess.getGroup_variablesAccess().getIdentifierAssignment_0(), "rule__Group_variables__IdentifierAssignment_0");
					put(grammarAccess.getGroup_variablesAccess().getBlockAssignment_1(), "rule__Group_variables__BlockAssignment_1");
					put(grammarAccess.getObservation_blockAccess().getIdentifierAssignment_0(), "rule__Observation_block__IdentifierAssignment_0");
					put(grammarAccess.getObservation_blockAccess().getBlockAssignment_1(), "rule__Observation_block__BlockAssignment_1");
					put(grammarAccess.getEstimation_blockAccess().getIdentifierAssignment_0(), "rule__Estimation_block__IdentifierAssignment_0");
					put(grammarAccess.getEstimation_blockAccess().getBlockAssignment_1(), "rule__Estimation_block__BlockAssignment_1");
					put(grammarAccess.getSimulation_blockAccess().getIdentifierAssignment_0(), "rule__Simulation_block__IdentifierAssignment_0");
					put(grammarAccess.getSimulation_blockAccess().getBlockAssignment_1(), "rule__Simulation_block__BlockAssignment_1");
					put(grammarAccess.getParam_obj_blockAccess().getStructural_blockAssignment_0(), "rule__Param_obj_block__Structural_blockAssignment_0");
					put(grammarAccess.getParam_obj_blockAccess().getVariability_blockAssignment_1(), "rule__Param_obj_block__Variability_blockAssignment_1");
					put(grammarAccess.getStructural_blockAccess().getIdentifierAssignment_0(), "rule__Structural_block__IdentifierAssignment_0");
					put(grammarAccess.getStructural_blockAccess().getBlockAssignment_1(), "rule__Structural_block__BlockAssignment_1");
					put(grammarAccess.getVariability_blockAccess().getIdentifierAssignment_0(), "rule__Variability_block__IdentifierAssignment_0");
					put(grammarAccess.getVariability_blockAccess().getBlockAssignment_1(), "rule__Variability_block__BlockAssignment_1");
					put(grammarAccess.getData_obj_blockAccess().getHeader_blockAssignment_0(), "rule__Data_obj_block__Header_blockAssignment_0");
					put(grammarAccess.getData_obj_blockAccess().getFile_blockAssignment_1(), "rule__Data_obj_block__File_blockAssignment_1");
					put(grammarAccess.getHeader_blockAccess().getIdentifierAssignment_0(), "rule__Header_block__IdentifierAssignment_0");
					put(grammarAccess.getHeader_blockAccess().getBlockAssignment_1(), "rule__Header_block__BlockAssignment_1");
					put(grammarAccess.getFile_blockAccess().getIdentifierAssignment_0(), "rule__File_block__IdentifierAssignment_0");
					put(grammarAccess.getFile_blockAccess().getBlockAssignment_1(), "rule__File_block__BlockAssignment_1");
					put(grammarAccess.getTask_obj_blockAccess().getFunction_declarationAssignment_0(), "rule__Task_obj_block__Function_declarationAssignment_0");
					put(grammarAccess.getTask_obj_blockAccess().getParameters_blockAssignment_1(), "rule__Task_obj_block__Parameters_blockAssignment_1");
					put(grammarAccess.getTask_obj_blockAccess().getData_blockAssignment_2(), "rule__Task_obj_block__Data_blockAssignment_2");
					put(grammarAccess.getParameters_blockAccess().getIdentifierAssignment_0(), "rule__Parameters_block__IdentifierAssignment_0");
					put(grammarAccess.getParameters_blockAccess().getBlockAssignment_1(), "rule__Parameters_block__BlockAssignment_1");
					put(grammarAccess.getData_blockAccess().getIdentifierAssignment_0(), "rule__Data_block__IdentifierAssignment_0");
					put(grammarAccess.getData_blockAccess().getBlockAssignment_1(), "rule__Data_block__BlockAssignment_1");
					put(grammarAccess.getModel_blockAccess().getStatementsAssignment_2(), "rule__Model_block__StatementsAssignment_2");
					put(grammarAccess.getModel_block_statementAccess().getStatementAssignment_0(), "rule__Model_block_statement__StatementAssignment_0");
					put(grammarAccess.getModel_block_statementAccess().getOde_blockAssignment_1(), "rule__Model_block_statement__Ode_blockAssignment_1");
					put(grammarAccess.getModel_block_statementAccess().getLibrary_blockAssignment_2(), "rule__Model_block_statement__Library_blockAssignment_2");
					put(grammarAccess.getLibrary_blockAccess().getIdentifierAssignment_0(), "rule__Library_block__IdentifierAssignment_0");
					put(grammarAccess.getLibrary_blockAccess().getBlockAssignment_1(), "rule__Library_block__BlockAssignment_1");
					put(grammarAccess.getOde_blockAccess().getIdentifierAssignment_0(), "rule__Ode_block__IdentifierAssignment_0");
					put(grammarAccess.getOde_blockAccess().getBlockAssignment_1(), "rule__Ode_block__BlockAssignment_1");
					put(grammarAccess.getVariability_block_contentAccess().getBlocksAssignment_2(), "rule__Variability_block_content__BlocksAssignment_2");
					put(grammarAccess.getVariability_block_statementAccess().getBlock_statementAssignment_0(), "rule__Variability_block_statement__Block_statementAssignment_0");
					put(grammarAccess.getVariability_block_statementAccess().getBlock_blockAssignment_1(), "rule__Variability_block_statement__Block_blockAssignment_1");
					put(grammarAccess.getVariability_block_statementAccess().getDiag_blockAssignment_2(), "rule__Variability_block_statement__Diag_blockAssignment_2");
					put(grammarAccess.getBlock_subblockAccess().getIdentifierAssignment_0(), "rule__Block_subblock__IdentifierAssignment_0");
					put(grammarAccess.getBlock_subblockAccess().getBlockAssignment_1(), "rule__Block_subblock__BlockAssignment_1");
					put(grammarAccess.getDiag_subblockAccess().getIdentifierAssignment_0(), "rule__Diag_subblock__IdentifierAssignment_0");
					put(grammarAccess.getDiag_subblockAccess().getBlockAssignment_1(), "rule__Diag_subblock__BlockAssignment_1");
					put(grammarAccess.getVariability_subblockAccess().getArgumentsAssignment_1(), "rule__Variability_subblock__ArgumentsAssignment_1");
					put(grammarAccess.getFile_block_contentAccess().getBlocksAssignment_2(), "rule__File_block_content__BlocksAssignment_2");
					put(grammarAccess.getFile_block_statementAccess().getStatementAssignment_0(), "rule__File_block_statement__StatementAssignment_0");
					put(grammarAccess.getFile_block_statementAccess().getInline_blockAssignment_1(), "rule__File_block_statement__Inline_blockAssignment_1");
					put(grammarAccess.getFile_block_statementAccess().getDesign_blockAssignment_2(), "rule__File_block_statement__Design_blockAssignment_2");
					put(grammarAccess.getFile_block_statementAccess().getRsscript_blockAssignment_3(), "rule__File_block_statement__Rsscript_blockAssignment_3");
					put(grammarAccess.getInline_blockAccess().getIdentifierAssignment_0(), "rule__Inline_block__IdentifierAssignment_0");
					put(grammarAccess.getInline_blockAccess().getBlockAssignment_1(), "rule__Inline_block__BlockAssignment_1");
					put(grammarAccess.getDesign_blockAccess().getIdentifierAssignment_0(), "rule__Design_block__IdentifierAssignment_0");
					put(grammarAccess.getDesign_blockAccess().getBlockAssignment_1(), "rule__Design_block__BlockAssignment_1");
					put(grammarAccess.getRsscript_blockAccess().getIdentifierAssignment_0(), "rule__Rsscript_block__IdentifierAssignment_0");
					put(grammarAccess.getRsscript_blockAccess().getBlockAssignment_1(), "rule__Rsscript_block__BlockAssignment_1");
					put(grammarAccess.getInline_block_contentAccess().getIdentifiersAssignment_2(), "rule__Inline_block_content__IdentifiersAssignment_2");
					put(grammarAccess.getInline_block_contentAccess().getValuesAssignment_3(), "rule__Inline_block_content__ValuesAssignment_3");
					put(grammarAccess.getFunction_declarationAccess().getIdentifierAssignment_0(), "rule__Function_declaration__IdentifierAssignment_0");
					put(grammarAccess.getFunction_declarationAccess().getFormal_argumentsAssignment_4(), "rule__Function_declaration__Formal_argumentsAssignment_4");
					put(grammarAccess.getFunction_declarationAccess().getFunction_bodyAssignment_6(), "rule__Function_declaration__Function_bodyAssignment_6");
					put(grammarAccess.getFunction_bodyAccess().getBlocksAssignment_2(), "rule__Function_body__BlocksAssignment_2");
					put(grammarAccess.getFunction_subblockAccess().getIdentifierAssignment_0_0(), "rule__Function_subblock__IdentifierAssignment_0_0");
					put(grammarAccess.getFunction_subblockAccess().getEstimate_defnAssignment_0_1(), "rule__Function_subblock__Estimate_defnAssignment_0_1");
					put(grammarAccess.getFunction_subblockAccess().getIdentifierAssignment_1_0(), "rule__Function_subblock__IdentifierAssignment_1_0");
					put(grammarAccess.getFunction_subblockAccess().getSimulate_defnAssignment_1_1(), "rule__Function_subblock__Simulate_defnAssignment_1_1");
					put(grammarAccess.getFormal_argumentsAccess().getIdentifiersAssignment_0(), "rule__Formal_arguments__IdentifiersAssignment_0");
					put(grammarAccess.getFormal_argumentsAccess().getIdentifiersAssignment_1_1(), "rule__Formal_arguments__IdentifiersAssignment_1_1");
					put(grammarAccess.getFunction_callAccess().getFunct_nameAssignment_0(), "rule__Function_call__Funct_nameAssignment_0");
					put(grammarAccess.getFunction_callAccess().getArgumentsAssignment_2(), "rule__Function_call__ArgumentsAssignment_2");
					put(grammarAccess.getBlockAccess().getStatementsAssignment_2(), "rule__Block__StatementsAssignment_2");
					put(grammarAccess.getBlock_statementAccess().getVariable_declarationAssignment_0(), "rule__Block_statement__Variable_declarationAssignment_0");
					put(grammarAccess.getBlock_statementAccess().getFunction_callAssignment_1(), "rule__Block_statement__Function_callAssignment_1");
					put(grammarAccess.getBlock_statementAccess().getStatementAssignment_2(), "rule__Block_statement__StatementAssignment_2");
					put(grammarAccess.getBlock_statementAccess().getVerbatim_blockAssignment_3(), "rule__Block_statement__Verbatim_blockAssignment_3");
					put(grammarAccess.getVerbatim_blockAccess().getIdentifierAssignment_0(), "rule__Verbatim_block__IdentifierAssignment_0");
					put(grammarAccess.getVerbatim_blockAccess().getBlockAssignment_2_0(), "rule__Verbatim_block__BlockAssignment_2_0");
					put(grammarAccess.getVerbatim_blockAccess().getExternal_codeAssignment_2_1(), "rule__Verbatim_block__External_codeAssignment_2_1");
					put(grammarAccess.getTarget_blockAccess().getIdentifierAssignment_0(), "rule__Target_block__IdentifierAssignment_0");
					put(grammarAccess.getTarget_blockAccess().getExternal_codeAssignment_2(), "rule__Target_block__External_codeAssignment_2");
					put(grammarAccess.getVariable_declarationAccess().getIdentifierAssignment_0(), "rule__Variable_declaration__IdentifierAssignment_0");
					put(grammarAccess.getVariable_declarationAccess().getExpressionAssignment_1_0_1(), "rule__Variable_declaration__ExpressionAssignment_1_0_1");
					put(grammarAccess.getVariable_declarationAccess().getRandom_listAssignment_1_1(), "rule__Variable_declaration__Random_listAssignment_1_1");
					put(grammarAccess.getAny_expressionAccess().getExpressionAssignment_0(), "rule__Any_expression__ExpressionAssignment_0");
					put(grammarAccess.getAny_expressionAccess().getListAssignment_1(), "rule__Any_expression__ListAssignment_1");
					put(grammarAccess.getAny_expressionAccess().getOde_listAssignment_2(), "rule__Any_expression__Ode_listAssignment_2");
					put(grammarAccess.getAny_expressionAccess().getRandom_listAssignment_3(), "rule__Any_expression__Random_listAssignment_3");
					put(grammarAccess.getExpressionAccess().getConditional_expressionAssignment_0(), "rule__Expression__Conditional_expressionAssignment_0");
					put(grammarAccess.getExpressionAccess().getString_expressionAssignment_1_0(), "rule__Expression__String_expressionAssignment_1_0");
					put(grammarAccess.getExpressionAccess().getString_expressionAssignment_1_1_1(), "rule__Expression__String_expressionAssignment_1_1_1");
					put(grammarAccess.getListAccess().getArgumentsAssignment_2(), "rule__List__ArgumentsAssignment_2");
					put(grammarAccess.getOde_listAccess().getArgumentsAssignment_2(), "rule__Ode_list__ArgumentsAssignment_2");
					put(grammarAccess.getRandom_listAccess().getArgumentsAssignment_2(), "rule__Random_list__ArgumentsAssignment_2");
					put(grammarAccess.getArgumentsAccess().getArgumentsAssignment_0(), "rule__Arguments__ArgumentsAssignment_0");
					put(grammarAccess.getArgumentsAccess().getArgumentsAssignment_1_1(), "rule__Arguments__ArgumentsAssignment_1_1");
					put(grammarAccess.getArgumentAccess().getIdentifierAssignment_0_0(), "rule__Argument__IdentifierAssignment_0_0");
					put(grammarAccess.getArgumentAccess().getExpressionAssignment_0_2(), "rule__Argument__ExpressionAssignment_0_2");
					put(grammarAccess.getArgumentAccess().getExpressionAssignment_1(), "rule__Argument__ExpressionAssignment_1");
					put(grammarAccess.getStatementAccess().getBlockAssignment_0(), "rule__Statement__BlockAssignment_0");
					put(grammarAccess.getStatementAccess().getPar_expressionAssignment_1_1(), "rule__Statement__Par_expressionAssignment_1_1");
					put(grammarAccess.getStatementAccess().getIf_statementAssignment_1_2(), "rule__Statement__If_statementAssignment_1_2");
					put(grammarAccess.getStatementAccess().getElse_statementAssignment_1_3_1(), "rule__Statement__Else_statementAssignment_1_3_1");
					put(grammarAccess.getPar_expressionAccess().getExpressionAssignment_1(), "rule__Par_expression__ExpressionAssignment_1");
					put(grammarAccess.getConditional_expressionAccess().getConditional_or_expressionAssignment_0(), "rule__Conditional_expression__Conditional_or_expressionAssignment_0");
					put(grammarAccess.getConditional_expressionAccess().getExpression1Assignment_1_1(), "rule__Conditional_expression__Expression1Assignment_1_1");
					put(grammarAccess.getConditional_expressionAccess().getExpression2Assignment_1_3(), "rule__Conditional_expression__Expression2Assignment_1_3");
					put(grammarAccess.getConditional_or_expressionAccess().getConditional_and_expressionAssignment_0(), "rule__Conditional_or_expression__Conditional_and_expressionAssignment_0");
					put(grammarAccess.getConditional_or_expressionAccess().getOperatorAssignment_1_0(), "rule__Conditional_or_expression__OperatorAssignment_1_0");
					put(grammarAccess.getConditional_or_expressionAccess().getConditional_and_expressionAssignment_1_1(), "rule__Conditional_or_expression__Conditional_and_expressionAssignment_1_1");
					put(grammarAccess.getConditional_and_expressionAccess().getRelational_expressionAssignment_0(), "rule__Conditional_and_expression__Relational_expressionAssignment_0");
					put(grammarAccess.getConditional_and_expressionAccess().getOperatorAssignment_1_0(), "rule__Conditional_and_expression__OperatorAssignment_1_0");
					put(grammarAccess.getConditional_and_expressionAccess().getRelational_expressionAssignment_1_1(), "rule__Conditional_and_expression__Relational_expressionAssignment_1_1");
					put(grammarAccess.getRelational_expressionAccess().getNegationAssignment_0(), "rule__Relational_expression__NegationAssignment_0");
					put(grammarAccess.getRelational_expressionAccess().getBooleanAssignment_1_0(), "rule__Relational_expression__BooleanAssignment_1_0");
					put(grammarAccess.getRelational_expressionAccess().getAdditive_expressionAssignment_1_1_0(), "rule__Relational_expression__Additive_expressionAssignment_1_1_0");
					put(grammarAccess.getRelational_expressionAccess().getRelational_opAssignment_1_1_1_0(), "rule__Relational_expression__Relational_opAssignment_1_1_1_0");
					put(grammarAccess.getRelational_expressionAccess().getAdditive_expressionAssignment_1_1_1_1(), "rule__Relational_expression__Additive_expressionAssignment_1_1_1_1");
					put(grammarAccess.getAdditive_expressionAccess().getMultiplicative_expressionAssignment_0(), "rule__Additive_expression__Multiplicative_expressionAssignment_0");
					put(grammarAccess.getAdditive_expressionAccess().getAdditive_opAssignment_1_0(), "rule__Additive_expression__Additive_opAssignment_1_0");
					put(grammarAccess.getAdditive_expressionAccess().getMultiplicative_expressionAssignment_1_1(), "rule__Additive_expression__Multiplicative_expressionAssignment_1_1");
					put(grammarAccess.getMultiplicative_expressionAccess().getPower_expressionAssignment_0(), "rule__Multiplicative_expression__Power_expressionAssignment_0");
					put(grammarAccess.getMultiplicative_expressionAccess().getMultiplicative_opAssignment_1_0(), "rule__Multiplicative_expression__Multiplicative_opAssignment_1_0");
					put(grammarAccess.getMultiplicative_expressionAccess().getPower_expressionAssignment_1_1(), "rule__Multiplicative_expression__Power_expressionAssignment_1_1");
					put(grammarAccess.getPower_expressionAccess().getUnary_expressionAssignment_0(), "rule__Power_expression__Unary_expressionAssignment_0");
					put(grammarAccess.getPower_expressionAccess().getPower_opAssignment_1_0(), "rule__Power_expression__Power_opAssignment_1_0");
					put(grammarAccess.getPower_expressionAccess().getUnary_expressionAssignment_1_1(), "rule__Power_expression__Unary_expressionAssignment_1_1");
					put(grammarAccess.getUnary_expressionAccess().getOperatorAssignment_0_0(), "rule__Unary_expression__OperatorAssignment_0_0");
					put(grammarAccess.getUnary_expressionAccess().getUnary_expressionAssignment_0_1(), "rule__Unary_expression__Unary_expressionAssignment_0_1");
					put(grammarAccess.getUnary_expressionAccess().getPar_expressionAssignment_1(), "rule__Unary_expression__Par_expressionAssignment_1");
					put(grammarAccess.getUnary_expressionAccess().getFunction_callAssignment_2(), "rule__Unary_expression__Function_callAssignment_2");
					put(grammarAccess.getUnary_expressionAccess().getPrimaryAssignment_3(), "rule__Unary_expression__PrimaryAssignment_3");
					put(grammarAccess.getPrimaryAccess().getNumberAssignment_0(), "rule__Primary__NumberAssignment_0");
					put(grammarAccess.getPrimaryAccess().getIdentifierAssignment_1(), "rule__Primary__IdentifierAssignment_1");
					put(grammarAccess.getVariable_nameAccess().getIdentifierAssignment_0(), "rule__Variable_name__IdentifierAssignment_0");
					put(grammarAccess.getVariable_nameAccess().getSelectorAssignment_1(), "rule__Variable_name__SelectorAssignment_1");
					put(grammarAccess.getVariable_nameAccess().getIdentifierAssignment_2_1(), "rule__Variable_name__IdentifierAssignment_2_1");
					put(grammarAccess.getVariable_nameAccess().getSelectorAssignment_2_2(), "rule__Variable_name__SelectorAssignment_2_2");
					put(grammarAccess.getSelectorAccess().getExpressionAssignment_1(), "rule__Selector__ExpressionAssignment_1");
					put(grammarAccess.getSelectorAccess().getExpressionAssignment_2_1(), "rule__Selector__ExpressionAssignment_2_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.ddmore.mdl.ui.contentassist.antlr.internal.InternalMdlParser typedParser = (org.ddmore.mdl.ui.contentassist.antlr.internal.InternalMdlParser) parser;
			typedParser.entryRulemcl();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
