package eu.ddmore.converter.mdl2pharmml08

import eu.ddmore.mdl.mdl.MclObject
import eu.ddmore.mdl.utils.MclUtils
import eu.ddmore.mdl.validation.MogValidator

import static eu.ddmore.converter.mdl2pharmml08.Constants.*

class Mdl2Pharmml {
	static val mdlVersion = "6.0"
	
	extension MogValidator mv = new MogValidator
	extension MclUtils mu = new MclUtils
	extension ModelDefinitionPrinter mdp = new ModelDefinitionPrinter
	extension ModellingStepsPrinter msp = new ModellingStepsPrinter
	extension FunctionDefinitionPrinter fdp = new FunctionDefinitionPrinter

  	def convertToPharmML(MclObject mog) {
  		mog.buildMog
		
		'''
		<?xml version="1.0" encoding="UTF-8"?>
		<PharmML 
			«printPharmMlNameSpaces»
			writtenVersion="«writtenVersion»">
			<ct:Name>"generated by MDL2PharmML v.«mdlVersion»"</ct:Name>
			<IndependentVariable symbId="«mdlObj.mdlIdv?.name ?: "T"»"/>
			«mv.mdlObj.writeFunctionDefinitions»	
			«mv.mdlObj.writeModelDefinition(paramObj)»
			«mv.writeModellingSteps»
		</PharmML>
		'''			
	}

	//+ Print PharmML namespaces
	protected def printPharmMlNameSpaces()
		'''
		xmlns:xsi="«xsi»" 
		xmlns="«xmlns_pharmML»"
		xsi:schemaLocation="«xsi_schemaLocation»"
		xmlns:math="«xmlns_math»"
		xmlns:ct="«xmlns_ct»"
		xmlns:ds="«xmlns_ds»"
		xmlns:mdef="«xmlns_mdef»"
		xmlns:mstep="«xmlns_mstep»"
		xmlns:design="«xmlns_design»"
		'''
}