/*
* generated by Xtext
*/
package org.ddmore.mdl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MdlOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
