/*
* generated by Xtext
*/
package org.ddmore.mdl.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractMdlJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.ddmore.mdl.mdl.MdlPackage.eINSTANCE);
		return result;
	}

}
