/*
 * generated by Xtext
 */
package org.ddmore.mdl.ui.contentassist

import org.ddmore.mdl.ui.contentassist.AbstractMdlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MdlProposalProvider extends AbstractMdlProposalProvider {
}
