/*
 * generated by Xtext
 */
package org.ddmore.mdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MdlUiModule extends org.ddmore.mdl.ui.AbstractMdlUiModule {
	public MdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
