/*
 * generated by Xtext
 */
package eu.ddmore.mdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MdlRuntimeModule extends eu.ddmore.mdl.AbstractMdlRuntimeModule {

//	@Override
//	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
//	  return NullGlobalScopeProvider.class;
//	}

//	@Override
//	public Class<? extends ILinkingService> bindILinkingService() {
//		return MdlLinkingService.class;
//	}

	
}
